### ISSUE TITLE
fail gracefully, if no headline matches

### ISSUE THREAD

**Issue by 2mc** [mutbuerger/company-org-headings#1]
Hello,
this is a very nice backend, indeed!

Only that your setup example suggests to use it as the one and only backend, if working in org-mode.
Most probably this isn't the case for most users. But if ''company-org-headings' get's inserted at the head to the list of 'company-beckends' it doesn't seem to fail gracefully (and return nil as one would expect here). Instead it seems to block the following beckends to handle possible completions at point.

**Comment by mutbuerger** [comment]
Hello,

thank you! Actually I'm using three backends in org-mode and can't reproduce this behavior. Have you checked the `company-backends` variable in one of your org files?

**Comment by 2mc** [comment]
My 'company-backends' list in org-mode looks like this.

       (company-math-symbols-unicode company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
                              (company-dabbrev-code company-gtags company-etags company-keywords)
                              company-oddmuse company-files company-dabbrev)

Take that simple case of completing something in org-mode where 'company-capf' will catch in, let's say:
    
     #+S

If you put the cursor behind the 'S' and call 

     M-x compony-complete 

you shall get the nice org-mode keywords condidates.

If that works for you, like for me, put 'company-org-headings' in front of 'company-backends' like this:

     (company-org-headings company-math-symbols-unicode company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
                      (company-dabbrev-code company-gtags company-etags company-keywords)
                      company-oddmuse company-files company-dabbrev)

and your above completion will fail, while posting:

     No completion found

**Comment by mutbuerger** [comment]
Hi!

This backend is generously accepting prefixes, sometimes not coming up with completion candidates for a grabbed prefix. As far as I understand `company`, this will block subsequent backends in the list. There are various ways to obtain the desired candidates: `company-other-backend` will skip the current candidates and proceed with the next backend. Also `company` allows to configure a group backend that merges the candidates of several backends. For example I used this setting:

    (setq company-backends
          '((company-org-headings company-dabbrev)))

to get candidates for both backends. Without the grouping, one backend will block the other depending on the accepted prefix and the order in the list. Changing the order is your next option. Restricting the prefix acceptance for this backend would be possible too, but I'm not sure how this could make any sense.

Best,
Bernhard

**Comment by 2mc** [comment]
Thank you for explaining the issue while pointing to company's prefix handling.
As a result, sensibly grouping backends, as your example has it, is our only option here.
Hinting to this option at the introductory page would be helpful, I guess, since poeple will naturally pump into this issue anyway, if they use more than one backend.
